# Generated by Django 3.1.7 on 2022-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[('男', 1), ('女', 2)], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
